// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.1
//
// <auto-generated>
//
// Generated from file `bank.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Client;

public class CreditDateRange extends com.zeroc.Ice.Value
{
    public CreditDateRange()
    {
    }

    public CreditDateRange(short month, short year)
    {
        this.month = month;
        this.year = year;
    }

    public short month;

    public short year;

    public CreditDateRange clone()
    {
        return (CreditDateRange)super.clone();
    }

    public static String ice_staticId()
    {
        return "::Client::CreditDateRange";
    }

    @Override
    public String ice_id()
    {
        return ice_staticId();
    }

    public static final long serialVersionUID = 774481265L;

    @Override
    protected void _iceWriteImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice(ice_staticId(), -1, true);
        ostr_.writeShort(month);
        ostr_.writeShort(year);
        ostr_.endSlice();
    }

    @Override
    protected void _iceReadImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        month = istr_.readShort();
        year = istr_.readShort();
        istr_.endSlice();
    }
}
