// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.1
//
// <auto-generated>
//
// Generated from file `bank.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Client;

public class CreditInfo extends com.zeroc.Ice.Value
{
    public CreditInfo()
    {
        this.currency = CurrencyType.PLN;
    }

    public CreditInfo(CurrencyType currency, float ratePerMonth)
    {
        this.currency = currency;
        this.ratePerMonth = ratePerMonth;
    }

    public CurrencyType currency;

    public float ratePerMonth;

    public CreditInfo clone()
    {
        return (CreditInfo)super.clone();
    }

    public static String ice_staticId()
    {
        return "::Client::CreditInfo";
    }

    @Override
    public String ice_id()
    {
        return ice_staticId();
    }

    public static final long serialVersionUID = 235646681L;

    @Override
    protected void _iceWriteImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice(ice_staticId(), -1, true);
        CurrencyType.ice_write(ostr_, currency);
        ostr_.writeFloat(ratePerMonth);
        ostr_.endSlice();
    }

    @Override
    protected void _iceReadImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        currency = CurrencyType.ice_read(istr_);
        ratePerMonth = istr_.readFloat();
        istr_.endSlice();
    }
}
